name: playerReputation
version: 2.1
main: creations.Reputation.main
api-version: 1.19

softdepend: [PlaceholderAPI]

commands:
  reputation:
    description: main prefix for inner commands
    usage: /<command>